### ISSUE TITLE
Activ Admin

### ISSUE THREAD

**Issue by svilder** [svilder/roger-vilder#39]
- [x] Fix bug when edit a work in production admin page -> exemple route redicted "https://localhost/admin/works/42"
- [ ] An Admin can delete a photo attached to a work
- [x] Better set for managing Texts, Bio, Exhibit, with appropriate filter and index display

**Comment by benjyarel** [comment]
close #39 .
We said a work must have a picture, it's a validation issue.
Roger vilder can change picture if he wants
