### ISSUE TITLE
Validations on models

### ISSUE THREAD

**Issue by svilder** [svilder/roger-vilder#47]
Some validations are commented, we need to think well and ask ourselves what info should always be there.

**Comment by benjyarel** [comment]
What could be important : 
- Validation with presence true  ( example : Works must have a picture, and a title)
for  exhibitions/biblio a year should be written, 
for texts : must have an author a title  ( maybe not a year)

**Comment by benjyarel** [comment]
@svilder  If you agree with me, say it to me, i'll do it in the day. you can add something if you want
